name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'

      - name: Install Dependncies
        run:  sudo npm install
      
      - name: tshirts pass
        run: "node tests/tshirtsTest.js"

      - name: misaligned pass
        run:  "node tests/misalignedTest.js"

      - name: transmitter pass
        run: "node tests/transmissionTest.js"
